version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres-container
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
    ports:
      - ":"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - postgres-net

networks:
  postgres-net:
    driver: bridge
